name: Deploy

on:
  push:
    tags:
      - "v*.*.*"

env:
  PROJECT_PATH: "Top Note/Top Note.csproj"

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" -c Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true
